---
# mackup_config/tasks/main.yml
# configures mackup via ~/.mackup.cfg

- name: check if ~/.mackup.cfg is present
  stat: path=~/.mackup.cfg
  register: mackupcfg_exists

- name: ensure ~/.mackup.cfg is present
  file: path=~/.mackup.cfg mode=0600 state=touch
  when: mackupcfg_exists.stat.exists == False

- name: configure .mackup.cfg
  ini_file: dest=~/.mackup.cfg follow=yes mode=0600 backup=yes
            section='{{ item.sect }}' option='{{ item.opt|default(omit) }}' value='{{ item.val }}'
  with_items:
      - { sect: storage , opt: engine , val: '{{ sync_engine }}' }
      - { sect: storage , opt: directory , val: '{{ sync_dir }}' }
      - { sect: applications_to_sync    , val: '{{ app_sync_list }}' }
      - { sect: applications_to_ignore  , val: '{{ app_ignore_list }}' }

- name: set the path when engine is file_system
  ini_file: dest=~/.mackup.cfg follow=yes mode=0600 backup=yes
            section='storage' option='path' value='{{ sync_path }}'
  when: sync_engine == "file_system" and sync_path is defined

