---
#mackup/meta/main.yml
dependencies:
- osxc.packages
#    brew_packages:
#        - mackup
#    cask_packages:
#        - {{ sync_engine | default(dropbox) }}
#
#  - role: mackup_config
#    sync_engine: dropbox
#    directory_name: mackup

