---

- hosts: all
  gather_facts: False
  roles:
  - role: osxc.packages
    brew_taps:
    - caskroom/fonts
# keepin it lean for now
    brew_packages:
    - ddrescue
    - figlet
    - htop
    - httpie
    - irssi
    - mackup
    - minicom
    - mtr
    - ncat
    - nmap
    - silc-client
    - tree
    - wget
    - whatmask
    brew_pkg_with_opts:
#    - { pkg: "curl" , opts: "with-idn,with-openssl" }
#    brew_package: curl
#    brew_opts: with-idn.with-openssl
    cask_packages:
    - box-sync
    - dash
    - font-inconsolata
    - font-source-code-pro
    - google-chrome
    - textmate

