---
- hosts: all
  gather_facts: False
  roles:
  - role: dock
    apps:
    - "/Applications/System Preferences.app"
    - /Applications/Utilities/Terminal.app
    - /Applications/TextMate.app
    - "/Applications/Google Chrome.app"
    folders:
    - path: ~/src/github.com
      view: grid
    - path: ~/Downloads
      sort: datemodified
      view: grid
